// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSY058WPlSLLgeqdjQWM-Sy2NM3tYFIQk',
    appId: '1:752828020174:web:8a1c2d98e0ded1dc47a79f',
    messagingSenderId: '752828020174',
    projectId: 'taskmanagement-9e535',
    authDomain: 'taskmanagement-9e535.firebaseapp.com',
    storageBucket: 'taskmanagement-9e535.firebasestorage.app',
    measurementId: 'G-XF2J6WNFDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzpCqXaMWU5OMYot1mc_pWAUhofviBMg0',
    appId: '1:752828020174:android:54803a5ab289aaf447a79f',
    messagingSenderId: '752828020174',
    projectId: 'taskmanagement-9e535',
    storageBucket: 'taskmanagement-9e535.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWZd8qRn9bVBx0OMpn4QbcLmV2As2tH1M',
    appId: '1:752828020174:ios:f847eee3e35433b647a79f',
    messagingSenderId: '752828020174',
    projectId: 'taskmanagement-9e535',
    storageBucket: 'taskmanagement-9e535.firebasestorage.app',
    iosBundleId: 'com.example.personalTaskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWZd8qRn9bVBx0OMpn4QbcLmV2As2tH1M',
    appId: '1:752828020174:ios:f847eee3e35433b647a79f',
    messagingSenderId: '752828020174',
    projectId: 'taskmanagement-9e535',
    storageBucket: 'taskmanagement-9e535.firebasestorage.app',
    iosBundleId: 'com.example.personalTaskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSY058WPlSLLgeqdjQWM-Sy2NM3tYFIQk',
    appId: '1:752828020174:web:2558063717252fae47a79f',
    messagingSenderId: '752828020174',
    projectId: 'taskmanagement-9e535',
    authDomain: 'taskmanagement-9e535.firebaseapp.com',
    storageBucket: 'taskmanagement-9e535.firebasestorage.app',
    measurementId: 'G-G4T3H350X8',
  );
}
